kind: Secret
apiVersion: v1
metadata:
  name: example-secret
  annotations:
    avp.kubernetes.io/path: "secret/data/avp"
    avp.kubernetes.io/kv-version: "1"
type: Opaque
stringData:
  sample: <sample>